version: 0.2
phases:
  install:
    commands:
      - npm install --verbose
      - npm install -g serverless --verbose
  pre_build:
    commands:
      - echo checking code quality...
      # - npx eslint -c .eslintrc.json --ext .js src/
  build:
    commands:
      # Will be using this in future for unit testing
      # - mocha test-application-code.js
  post_build:
    commands:
      - aws s3 sync build s3://$DEPLOYMENT_BUCKET/ --delete --exclude 'index.html' --acl public-read --cache-control 'max-age=860000'
      - aws s3 sync build s3://$DEPLOYMENT_BUCKET/ --delete --exclude '*' --include 'index.html' --acl public-read --cache-control 'max-age=0'
