service:
  name: nodejs-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "2"

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
provider:
  name: aws
  region: 'us-east-2'
  stage: 'dev'
  role: arn:aws:iam::217392961699:role/service-role/poc_test_keygeneration-role-rc5jqm8f
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  thumbnail:
    handler: handlers/thumbnail-sharp.createThumbnail
    events:
      - httpApi:
          method: get
          path: /thumbnail
  JIMPthumbnail:
    handler: handlers/thumbnail-jimp.createThumbnail
    events:
      - httpApi:
          method: get
          path: /jimp
  
